version: '3.8'

services:
  web:
    build: .
    command: gunicorn tourism_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - db
    restart: always
    environment:
      - REBUILD_DB=${REBUILD_DB:-false}

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.docker
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
