services:
  - type: web
    name: tourism-project
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn tourism_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: RENDER
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: tourism-db
          property: connectionString
      - key: PAYPAL_MODE
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

databases:
  - name: tourism-db
    databaseName: tourism
    user: tourism_user
