# Generated by Django 5.2 on 2025-04-05 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('subject_ar', models.CharField(max_length=200, null=True, verbose_name='Subject')),
                ('subject_en', models.CharField(max_length=200, null=True, verbose_name='Subject')),
                ('subject_fr', models.CharField(max_length=200, null=True, verbose_name='Subject')),
                ('subject_nl', models.CharField(max_length=200, null=True, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_ar', models.TextField(null=True, verbose_name='Message')),
                ('message_en', models.TextField(null=True, verbose_name='Message')),
                ('message_fr', models.TextField(null=True, verbose_name='Message')),
                ('message_nl', models.TextField(null=True, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Currency Name')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='Currency Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Currency Name')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='Currency Name')),
                ('name_nl', models.CharField(max_length=100, null=True, verbose_name='Currency Name')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Currency Code')),
                ('symbol', models.CharField(max_length=5, verbose_name='Currency Symbol')),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Exchange Rate to Base Currency')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('question_ar', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('question_en', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('question_fr', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('question_nl', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('answer_ar', models.TextField(null=True, verbose_name='Answer')),
                ('answer_en', models.TextField(null=True, verbose_name='Answer')),
                ('answer_fr', models.TextField(null=True, verbose_name='Answer')),
                ('answer_nl', models.TextField(null=True, verbose_name='Answer')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Subscribed At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_ar', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_fr', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_nl', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_ar', models.TextField(null=True, verbose_name='Message')),
                ('message_en', models.TextField(null=True, verbose_name='Message')),
                ('message_fr', models.TextField(null=True, verbose_name='Message')),
                ('message_nl', models.TextField(null=True, verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('system', 'System'), ('promotion', 'Promotion')], max_length=20, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='Site Name')),
                ('site_name_ar', models.CharField(max_length=100, null=True, verbose_name='Site Name')),
                ('site_name_en', models.CharField(max_length=100, null=True, verbose_name='Site Name')),
                ('site_name_fr', models.CharField(max_length=100, null=True, verbose_name='Site Name')),
                ('site_name_nl', models.CharField(max_length=100, null=True, verbose_name='Site Name')),
                ('site_logo', models.ImageField(upload_to='site/', verbose_name='Site Logo')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('address', models.TextField(verbose_name='Address')),
                ('address_ar', models.TextField(null=True, verbose_name='Address')),
                ('address_en', models.TextField(null=True, verbose_name='Address')),
                ('address_fr', models.TextField(null=True, verbose_name='Address')),
                ('address_nl', models.TextField(null=True, verbose_name='Address')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube URL')),
                ('about_us', models.TextField(blank=True, verbose_name='About Us')),
                ('about_us_ar', models.TextField(blank=True, null=True, verbose_name='About Us')),
                ('about_us_en', models.TextField(blank=True, null=True, verbose_name='About Us')),
                ('about_us_fr', models.TextField(blank=True, null=True, verbose_name='About Us')),
                ('about_us_nl', models.TextField(blank=True, null=True, verbose_name='About Us')),
                ('privacy_policy', models.TextField(blank=True, verbose_name='Privacy Policy')),
                ('privacy_policy_ar', models.TextField(blank=True, null=True, verbose_name='Privacy Policy')),
                ('privacy_policy_en', models.TextField(blank=True, null=True, verbose_name='Privacy Policy')),
                ('privacy_policy_fr', models.TextField(blank=True, null=True, verbose_name='Privacy Policy')),
                ('privacy_policy_nl', models.TextField(blank=True, null=True, verbose_name='Privacy Policy')),
                ('terms_conditions', models.TextField(blank=True, verbose_name='Terms and Conditions')),
                ('terms_conditions_ar', models.TextField(blank=True, null=True, verbose_name='Terms and Conditions')),
                ('terms_conditions_en', models.TextField(blank=True, null=True, verbose_name='Terms and Conditions')),
                ('terms_conditions_fr', models.TextField(blank=True, null=True, verbose_name='Terms and Conditions')),
                ('terms_conditions_nl', models.TextField(blank=True, null=True, verbose_name='Terms and Conditions')),
                ('default_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_currency', to='core.currency', verbose_name='Default Currency')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
