# Generated by Django 4.2.20 on 2025-04-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # Removed RenameField operations due to SQLite limitations with django-modeltranslation
        # modeltranslation will handle the necessary schema changes based on models.py and settings.py
    ]
