# Generated by Django 5.2 on 2025-04-23 15:30

from django.db import migrations, models
from django.db import connection


def column_exists(table_name, column_name):
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name=? AND sql LIKE ?",
            [table_name, f'%{column_name}%']
        )
        return cursor.fetchone()[0] > 0


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_message_nl_contactmessage_message_de_and_more'),
    ]

    operations = [
        # Currency model changes - these are safe to add
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code'], 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AddField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=10),
        ),
    ]