# Generated by Django 5.2 on 2025-04-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250422_combined'),
        ('core', '0003_auto_20250423_combined'),
    ]

    operations = [
    ]
