# Generated by Django 5.2 on 2025-04-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250423_safe'),
        ('core', '0004_merge_20250423_1638'),
    ]

    operations = [
    ]
