# Generated by Django 5.2 on 2025-05-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_site'),
        ('core', '0008_fix_duplicate_columns'),
        ('core', '0008_fix_translation_fields'),
    ]

    operations = [
    ]
