# Generated by Django 5.2 on 2025-05-02 11:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour', '0004_rename_description_nl_activity_description_de_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('path', models.CharField(max_length=255, verbose_name='Path')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='Referer')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Site Visit',
                'verbose_name_plural': 'Site Visits',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='analytics_s_timesta_be3aae_idx'), models.Index(fields=['ip_address'], name='analytics_s_ip_addr_110372_idx'), models.Index(fields=['country'], name='analytics_s_country_ab6e49_idx')],
            },
        ),
        migrations.CreateModel(
            name='TourView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_views', to='tour.tour', verbose_name='Tour')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_views', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Tour View',
                'verbose_name_plural': 'Tour Views',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='analytics_t_timesta_0b87c4_idx'), models.Index(fields=['tour'], name='analytics_t_tour_id_f67569_idx')],
                'unique_together': {('tour', 'ip_address', 'user', 'session_key')},
            },
        ),
    ]
