# Generated by Django 4.2.20 on 2025-04-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='description_nl',
            new_name='description_de',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='name_nl',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description_nl',
            new_name='description_de',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_nl',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='description_nl',
            new_name='description_de',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='name_nl',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='description_nl',
            new_name='description_de',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='title_nl',
            new_name='title_de',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='description_nl',
            new_name='description_de',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='excluded_services_nl',
            new_name='excluded_services_de',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='included_services_nl',
            new_name='included_services_de',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='meeting_point_nl',
            new_name='meeting_point_de',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='name_nl',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='short_description_nl',
            new_name='short_description_de',
        ),
        migrations.RenameField(
            model_name='tourfaq',
            old_name='answer_nl',
            new_name='answer_de',
        ),
        migrations.RenameField(
            model_name='tourfaq',
            old_name='question_nl',
            new_name='question_de',
        ),
        migrations.RenameField(
            model_name='tourguide',
            old_name='bio_nl',
            new_name='bio_de',
        ),
        migrations.RenameField(
            model_name='tourguide',
            old_name='languages_nl',
            new_name='languages_de',
        ),
        migrations.RenameField(
            model_name='touritinerary',
            old_name='accommodation_nl',
            new_name='accommodation_de',
        ),
        migrations.RemoveField(
            model_name='touritinerary',
            name='description_nl',
        ),
        migrations.RemoveField(
            model_name='touritinerary',
            name='meals_nl',
        ),
        migrations.RemoveField(
            model_name='touritinerary',
            name='title_nl',
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='meals_de',
            field=models.CharField(blank=True, help_text='E.g., Breakfast, Lunch, Dinner', max_length=100, null=True, verbose_name='Meals'),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='title_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
