# Generated by Django 5.2 on 2025-05-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_rename_description_nl_activity_description_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='difficulty',
        ),
    ]
