# Generated by Django 5.2 on 2025-04-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_total_price'),
        ('booking', '0003_booking_discount_amount_booking_subtotal'),
    ]

    operations = [
    ]
