# Generated by Django 5.2 on 2025-04-05 17:40

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_nl', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_nl', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_nl', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_nl', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO Title')),
                ('seo_title_ar', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO Title')),
                ('seo_title_en', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO Title')),
                ('seo_title_fr', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO Title')),
                ('seo_title_nl', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Description')),
                ('seo_description_ar', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO Description')),
                ('seo_description_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO Description')),
                ('seo_description_fr', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO Description')),
                ('seo_description_nl', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO Description')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/categories/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_nl', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('excerpt', models.TextField(max_length=500, verbose_name='Excerpt')),
                ('excerpt_ar', models.TextField(max_length=500, null=True, verbose_name='Excerpt')),
                ('excerpt_en', models.TextField(max_length=500, null=True, verbose_name='Excerpt')),
                ('excerpt_fr', models.TextField(max_length=500, null=True, verbose_name='Excerpt')),
                ('excerpt_nl', models.TextField(max_length=500, null=True, verbose_name='Excerpt')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('content_ar', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_fr', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_nl', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO Title')),
                ('seo_title_ar', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO Title')),
                ('seo_title_en', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO Title')),
                ('seo_title_fr', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO Title')),
                ('seo_title_nl', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Description')),
                ('seo_description_ar', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO Description')),
                ('seo_description_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO Description')),
                ('seo_description_fr', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO Description')),
                ('seo_description_nl', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO Description')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/posts/')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Allow comments')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='posts', to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('content', models.TextField(verbose_name='Content')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/posts/')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post')),
            ],
            options={
                'verbose_name': 'Post Image',
                'verbose_name_plural': 'Post Images',
                'ordering': ['position'],
            },
        ),
    ]
