# Generated by Django 4.2.20 on 2025-04-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description_nl',
            new_name='description_de',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_nl',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='seo_description_nl',
            new_name='seo_description_de',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='seo_title_nl',
            new_name='seo_title_de',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='excerpt_nl',
            new_name='excerpt_de',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='seo_description_nl',
            new_name='seo_description_de',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='seo_title_nl',
            new_name='seo_title_de',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_nl',
            new_name='title_de',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='description_nl',
            new_name='description_de',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name_nl',
            new_name='name_de',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_nl',
        ),
        migrations.AddField(
            model_name='post',
            name='content_de',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_ar',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_fr',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
    ]
