# Generated by Django 4.2.20 on 2025-04-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment_nl',
            new_name='comment_de',
        ),
    ]
