# Generated by Django 5.2 on 2025-04-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_comment_nl_review_comment_de'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Is Approved'),
        ),
    ]
